// Made with love by Ryan Boyer http://ryanjboyer.com <3

namespace Easings
{
    public enum EasingType
    {
        Custom = -1,
        Linear,
        ExpoOut,
        ExpoIn,
        ExpoInOut,
        ExpoOutIn,
        CircOut,
        CircIn,
        CircInOut,
        CircOutIn,
        QuadOut,
        QuadIn,
        QuadInOut,
        QuadOutIn,
        SineOut,
        SineIn,
        SineInOut,
        SineOutIn,
        CubicOut,
        CubicIn,
        CubicInOut,
        CubicOutIn,
        QuartOut,
        QuartIn,
        QuartInOut,
        QuartOutIn,
        QuintOut,
        QuintIn,
        QuintInOut,
        QuintOutIn,
        ElasticOut,
        ElasticIn,
        ElasticInOut,
        ElasticOutIn,
        BounceOut,
        BounceIn,
        BounceInOut,
        BounceOutIn,
        BackOut,
        BackIn,
        BackInOut,
        BackOutIn
    }
}